- test: main
  description: >
  gen_opts: >
    +instr_cnt=3500
    +num_of_sub_programs=20
    +uvm_set_type_override=riscv_instr_gen_config,riscv_instr_gen_config_ext
    +directed_instr_0=riscv_hazard_instr_stream,4
    +directed_instr_1=riscv_int_numeric_corner_stream,4
    +directed_instr_2=riscv_loop_instr,4
    +directed_instr_3=riscv_jal_instr,4
    +directed_instr_4=riscv_load_store_hazard_instr_stream,4
    +directed_instr_5=riscv_load_store_stress_instr_stream,4
    +directed_instr_6=riscv_multi_page_load_store_instr_stream,4
    +directed_instr_7=riscv_mem_region_stress_test,4
    +no_ecall=1
    +no_fence=1
    +no_csr_instr=1
    +boot_mode=m
  iterations: 1
  gen_test: riscv_instr_base_test
  rtl_test: core_base_test