- test: main
  description: >
  mem_region:
    # 1. IMEM (SRAM) - 存放 Boot Code 或部分指令
    - name: imem
      size_in_bytes: 65536      # 64KB (0x10000)
      start_addr: "0x00010000"
      permission: rx            # Read-Execute (程式碼)
    
    # 2. DMEM (SRAM) - 存放部分 Data
    - name: dmem
      size_in_bytes: 65536      # 64KB (0x10000)
      start_addr: "0x00020000"
      permission: rw            # Read-Write (資料)

    # 4. DRAM_D (DRAM) - 存放大量資料
    - name: dram_d
      size_in_bytes: 1048576    # 1MB (0x100000)
      start_addr: "0x20100000"
      permission: rw            # Read-Write (資料)
  
  gen_opts: >
    +instr_cnt=5000
    +num_of_sub_programs=40
    +uvm_set_type_override=riscv_instr_gen_config,riscv_instr_gen_config_ext
    +directed_instr_0=riscv_hazard_instr_stream,5
    +directed_instr_1=riscv_int_numeric_corner_stream,5
    +directed_instr_2=riscv_loop_instr,5
    +directed_instr_3=riscv_jal_instr,5
    +directed_instr_4=riscv_load_store_hazard_instr_stream,5
    +directed_instr_5=riscv_load_store_stress_instr_stream,5
    +directed_instr_6=riscv_multi_page_load_store_instr_stream,5
    +directed_instr_7=riscv_mem_region_stress_test,5
    +no_ecall=1
    +no_fence=1
    +no_csr_instr=1
    +boot_mode=m
  iterations: 1
  gen_test: riscv_instr_base_test
  rtl_test: core_base_test